apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bonus-playground
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: bonus.playground.localhost # /etc/hosts -> 127.0.0.1 bonus.playground.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bonus-playground
                port:
                  number: 80
