global:
  edition: ce
  hosts:
    domain: localhost
    externalIP: 127.0.0.1
    https: false
  ingress:
    enabled: false
    configureCertmanager: false
  minio:
    enabled: false
  gitaly:
    enabled: false
    external:
      - name: default
        host: dummy.local
  appConfig:
    artifacts:
      enabled: false
      connection: {}
    lfs:
      enabled: false
      connection: {}
    uploads:
      enabled: false
      connection: {}
    packages:
      enabled: false
      connection: {}

certmanager:
  enabled: false

nginx-ingress:
  enabled: false

prometheus:
  install: false

gitlab-runner:
  install: false

registry:
  enabled: false

gitlab:
  webservice:
    replicaCount: 1
  sidekiq:
    enabled: false
  toolbox:
    enabled: false
  kas:
    enabled: false

postgresql:
  persistence:
    enabled: false

redis:
  persistence:
    enabled: false
